### ISSUE TITLE
Setting up CI releases for version 1.0

### ISSUE THREAD

**Issue by jenshalm** [typelevel/Laika#430]
With the 0.19 maintenance branch now in place we can change the build for the `main` branch now.

The plan for the first 1.0 milestone release is:

* The organisation needs to change to `org.typelevel`.
* The first release is `1.0.0-M1`.
* We can skip publishing of manual and API for now. We can look into this for the 2nd milestone. There are still some weird issues with unidoc output that currently requires manual intervention before publishing.
* Nevertheless the steps `docs/mdoc` and `docs/laikaSite` should be included for validation.
* mima checks need to be off for the milestones.
* `plugin/scripted` should ideally run as the very last step as it is so much slower than all the other steps. Ideally it should also only run on one Java version in case the other steps run on multiple, but I'm not sure if that's possible.

@armanbilge if you want to use Laika for testing the `sbt-typelevel` RC, feel free. The release can happen any time now, the only PR that should go in is #429 which is good to go and can be merged anytime.

**Comment by armanbilge** [comment]
Our first CI-published snapshot:
https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/laika-sbt_2.12_1.0/
