### ISSUE TITLE
Include local url in laikaPreview console message

### ISSUE THREAD

**Issue by davesmith00000** [typelevel/Laika#494]
Hi,

I've been playing around with Laika and it's working really well.

A tiny quality of life enhancing improvement would be to alter [this message](https://github.com/typelevel/Laika/blob/dd872237fb552c8f8b4119a3c02ab2e55bad96fb/sbt/src/main/scala/laika/sbt/Tasks.scala#L256), from:

`Preview server started on port 4242. Press return/enter to exit.`

To something like:

`Preview server started at http://localhost:4242. Press return/enter to exit.`

Most terminals will recognise a url, and this would allow people to click and immediately open their site in the default browser. Most if not all of the other similar tools I use do this.

Feel free to close this issue if there are good reasons not to do so.

Thanks!

**Comment by jenshalm** [comment]
Hello there and welcome. I am not aware of any downsides for making this change and it's trivial to do so.
Unless someone comes up with any objections, I can include this in the next release (0.19.4).
