### ISSUE TITLE
Incorrect ScalaDoc for InputTreeBuilder

### ISSUE THREAD

**Issue by noelwelsh** [typelevel/Laika#575]
The example code in the ScalaDoc for `InputTreeBuilder`  seems to be broken.

https://github.com/typelevel/Laika/blob/f0970fb8a5febccb7352bd92ab14ae4cdd41efd0/io/src/main/scala/laika/io/model/InputTreeBuilder.scala#L68

Shouldn't this be `InputTreeBuilder`, not `InputTree`? Also, there is no method `addClasspathResource`, which occurs a few lines later in the example.

**Comment by jenshalm** [comment]
`InputTree[F]` is actually correct, the `apply` does create a builder. But `addClasspathResource` is indeed outdated, that was 0.18 API (that also did not work reliably under some class loaders). In 0.19 and 1.0 it's either `addClassResource` or `addClassLoaderResource` which both now just delegate to the corresponding fs2 methods.
